### ISSUE TITLE
In the license file at offset 2Ch, the total password length is stored.

### ISSUE THREAD

**Issue by whizzzzzzz** [izacktheyak/k9wppc#1]
It can be done easier, loop in the password decryption process as much as times as offset 2Ch in the license file contains. The length of the password is in 2Ch.
Once you've done that, you're all set. No need to wait for illegal characters.
An encrypted email address for administration is included in the license file too, but that's another case.

Look at ' https://github.com/uBitz/BlueCoatK9-Version4.X-PwdDec/tree/main '

**Comment by whizzzzzzz** [comment]
Excuse me, the password length is at 0B4h.

**Comment by yak-was-here** [comment]
I haven't touched this in 8 years. Submit a PR and I will look over it.

**Comment by whizzzzzzz** [comment]
Hi,

The password length is at 0B4h and cannot be more than 0Fh characters, including an ending zero (15 characters long).
I'll look if I can find my Github password. 😉
Take a look at the assembly program I posted for you, it's much quicker. It can be compiled using MASM32.


Greetings,
kattekop

________________________________
Van: isaacyakl ***@***.***>
Verzonden: maandag 1 april 2024 15:25
Aan: isaacyakl/k9wppc ***@***.***>
CC: whizzzzzzz ***@***.***>; Author ***@***.***>
Onderwerp: Re: [isaacyakl/k9wppc] In the license file at offset 2Ch, the total password length is stored. (Issue #1)


I haven't touched this in 8 years. Submit a PR and I will look over it.

**Comment by whizzzzzzz** [comment]
I can't post a Pull Request, as I can't code in C++. Can you fix it? Thanks so much.
